- hosts: web
  remote_user: root
  become: yes
  tasks:
  - name: Update Packages
    yum:
      state: latest

  - name: Install Apache
    yum:
      name: httpd
      state: installed
    notify:
      - Restart Apache

  - name: HTML Packages
    shell: 
      cmd: echo "Hello from Ansible Challenge" >> /var/www/html/index.html
    notify:
      - Restart Apache

  - name: Curl Web
    shell:
      cmd: curl http://169.254.169.254/latest/meta-data/public-ipv4
    register: curl
  - debug: var=curl.stdout_lines      

  handlers:
  - name: Restart Apache
    service:
      name: httpd
      state: restarted